# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gmmr <- function(data, datac, k, pi0, mu0, sd0) {
    .Call(`_gmlfdr_gmmr`, data, datac, k, pi0, mu0, sd0)
}

